package com.bangbangas.exception;

public class TestSub {
    public static void main(String[] args)  {
//        Scanner scanner = new Scanner(System.in);
//        try {
//            System.out.println("请录入第一个数");
//            int i = scanner.nextInt();
//            System.out.println("请录入第二个数");
//            int i1 = scanner.nextInt();
//            System.out.println("hahahahhahah");
//            System.out.println("商为 "+i/i1);
//        } catch (Exception e) {
//            e.printStackTrace();
//        } finally {
//            scanner.close();
//        }
//        System.out.println("111111111111111111");

         Person person = new Person("wangshaobo",10,"haha");
    }
}
